### ISSUE TITLE
ph example can easily be solved by llms

### ISSUE THREAD

**Issue by RedMoon32** [neurallambda/neurallambda#2]
I used [chatbot arena](https://chat.lmsys.org/)  to test different networks with the given puzzle in readme and most of the models actually solve 
it pretty easily

examples:
<img width="1529" alt="image" src="https://github.com/neurallambda/neurallambda/assets/31774217/62ec8de8-f621-4261-bf07-7660b606383e">

<img width="1542" alt="image" src="https://github.com/neurallambda/neurallambda/assets/31774217/204ea4a8-fbe4-49ae-8981-d87e7e898b79">

**Comment by freckletonj** [comment]
Thanks for double checking me. A couple things:

* they all failed to "simply output your answer", eg they should say just `4.5 - 5.5`, so that's the first reasoning failure.
* gpt4, when i ran it, said bananas, even though it tried (incorrectly) to CoT a little, and no human would ever get it *that* wrong (yellow??)
* For an interesting discussion that recently blew up in this same vein but is a little more dealing with formal grammars, check out: https://twitter.com/VictorTaelin/status/1776096481704804789 . In the end someone solves this incredibly narrow, short problem with incredibly large prompts, which I feel like proves my point. LLMs can't do induction, IE they cannot reason about things bigger than their context window, or even things within their context window.
* If you *really* want to prove to yourself that it can't reason, ask it to help write custom concurrent code, something far enough outside the domain of what it's memorized. This requires it having an understanding of what the state looks like in different components at different times. It falls flat on its face. I was using it to help with `uniteai` which uses an Actor model in the backend. It was hot garbage (gpt4).
* It's easy to craft prompts that they suck at, namely, anything that requires reasonign symbolically, and it didn't memorize pieces that can be recombined into an answer. I just tried one with chat gpt again that maybe will convince you. I gave 2 tries at crafting this prompt. On the first it wanted to use python, so I asked it not to. So, not a cherry picked prompt.

```
please continue this series for as long as you can, directly without using a python interpreter:

```
if even: y = 5x - 3
if odd: y = 2x + 2
```


We'll start from 1000.

1000 4997 9996 49977

---------------

Let's continue this sequence.

    Step 1: 1000 is even, so we use the even formula y=5x−3y=5x−3. 1000→49971000→4997.
    Step 2: 4997 is odd, so we use the odd formula y=2x+2y=2x+2. 4997→99964997→9996.
    Step 3: 9996 is even, so again with the even formula. 9996→499779996→49977.

Continuing from 49977, which is odd:

    Step 4: For x=49977x=49977, y=2x+2=99956+2=99958y=2x+2=99956+2=99958.
    Step 5: For x=99958x=99958, y=5x−3=499790−3=499787y=5x−3=499790−3=499787.
    Step 6: For x=499787x=499787, y=2x+2=999574+2=999576y=2x+2=999574+2=999576.
    Step 7: For x=999576x=999576, y=5x−3=4997880−3=4997877y=5x−3=4997880−3=4997877.

So the continuation is: 99958, 499787, 999576, 4997877.
```

It messes up on the very first continuation, step 4 (which should be 99956). 


**Rebutals:**

* The tokenizer likely hinders it in problems like this so is that the issue? Craft a problem where the tokenizer doesn't hinder it, and it'll still suffer. I experience this all day during using AI. It suffers from something I call bayesian bias (just in my own mind, it's not "a thing"). For a caricature of this effect, it's like you've said in dialog several times that `x=2` and then change it `now x=10`. All of those `x=2`s bias it so that it moves in the direction of `x=10`, but not `x=10`. For a non-caricature of this, if I iteratively change a piece of code with AI, the first versions of undue sway over later versions, ie it will revive and suggest old useless broken versions of code. The best remedy is starting a new chat from scratch. It can't ignore things you've told it to ignore.

* multi-hop reasoning can't be done in one step (unless the data is memorized, ie not reasoning, and also you'd need to approach infinite data). So you do need iterated thinking which my prompt trys to forbid (and the model fails to follow, which is a failure of reasoning). Neurallambda would also need iterated thinking, though instead of Chain-of-thought, it'd be doing the thinking directly in the latent space.
* So is the issue that I forbade it the requisite time to think? That ex I wanted to be short and pithy. Here's a new problem I just tried, and gave it "as much time" as it wanted. This prompt was also not cherry picked. On my first try I included no "a"s and it correctly gave `[]`. This is my second try:

```
I'll give you a mapping of ints to strings, please return only the indexes of the items that start with "a", and make sure the list of ints you give me are sorted alphabetically according to the english name of the numbers (ie not according to the text).

Ex for this mapping:

{
1: "zoo",
2: "air",
3: "advance"
}

You would return: `[3, 2]`

Here's your mapping, take as long as you need to think it through, but do not use a code interpreter.

{
3: "happy",
5: "cry",
9: "cup",
11: "wow",
17: "sky",
42: "bird",
4: "house",
12: "love",
19: "aa",
18: "ab",
100: "ac",
101: "ad",
6: "ae"
}

--------------------

To solve this task, let's first filter the given mapping for items that start with "a", and then sort the indexes (keys) of those items alphabetically according to the English name of the numbers. The steps are as follows:

1. **Filter the mapping for items starting with "a":**

   - 19: "aa"
   - 18: "ab"
   - 100: "ac"
   - 101: "ad"
   - 6: "ae"

2. **Sort the indexes according to the English names of the numbers:**

   - Six (6)
   - Eighteen (18)
   - Nineteen (19)
   - One hundred (100)
   - One hundred one (101)

So, the sorted list of indexes, based on the English names of the numbers, would be: `[6, 18, 19, 100, 101]`.
```

**Comment by freckletonj** [comment]
I don't mean to swamp you with too much, i'm still curious if you have a response, especially if you found the above non persuasive!

**Comment by RedMoon32** [comment]
thank you very much I found your answer deeply explained and detailed! Of course I know that it lacks true reasoning (it cannot even solve simple div3 problems from the codeforces) just wanted to point out that maybe better to change the reasoning example but it kinda minor details not really influencing anything so dont mind)

**Comment by RedMoon32** [comment]
btw the question - is this repo similar to this article https://arxiv.org/pdf/2207.02098.pdf ?

**Comment by freckletonj** [comment]
totally thank you, i discovered that article part way into developing this stuff, don't know how it skipped my radar for that long!

I think I'll be able to improve on those results, but, time will tell!
